#!/usr/bin/env bash
#bash script

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | tee /var/www/html/index.html
sudo service nginx start
sudo sed -i 's/^(?!#)\s*location \/ {/location \/ {\n\t\t add_header X-Served-By $server_name;/' /etc/nginx/sites-available/default
sudo nginx -s reload
