#!/usr/bin/env bash
# hello
for ((i=1 ; i<=100 ; i++));
do
    if [ $((i%3)) == 0 ]; then
        echo -n "Fizz"
    fi
    if [ $((i%5)) == 0 ]; then
        echo -n "Buzz"
    fi
    if (( $((i%3)) == 0 || $((i%5)) == 0 )); then
        echo ""
    else
        echo $i
    fi

done