#!/usr/bin/env bash
# comment?

if [ -e "school" ]; then
    echo "school file exist"
    if [ -s "school" ]; then
        echo "school file is not empty"
        if [ -f "school" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file empty"
    fi
else
    echo "school file does not exist"
fi